#!/bin/sh

files=$(git diff --cached --name-only --diff-filter=ACM | grep ".ts$")
if [ "$files" = "" ]; then 
    exit 0 
fi

pass=true

echo "Running TSLint..."

if yarn lint; then
   echo "Success"
else
   echo "Failed"
   pass=false
fi
